POST http://localhost:4000/api/contacts
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhjMWE1MjI2NmQzYWZmZWUxOTYxMGYiLCJpYXQiOjE2ODY5MTIyMTMsImV4cCI6MTY4NzUxNzAxM30.2HxCaHTFqSQj9mTJXFz5CDqBIlcjp9barI9aget-Ask

{"firstName":"abike", "lastName":"Dabiri", "contactInfo":{"phone":"08037205072", "email":"abike@gmail.com", "city":"Abuja"}, "image":"", "category":"friend"}