GET http://localhost:4000/api/contacts/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGMyOGZjYWFmMzYxZDE0NGI3ZjQ4OWQiLCJpYXQiOjE2OTI5NDYwNDAsImV4cCI6MTY5MzU1MDg0MH0.Lz9dP8HKVLkXBVhBuOl-wU6GZ2gNF2_IraCQeEp1JxM